name: Module Build, Test and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
    tags:
      - v*
    #tags-ignore:
    #- '*-*'
  pull_request:
  workflow_dispatch:

env:
  buildFolderName: output
  buildArtifactName: output
  testResultFolderName: testResults
  defaultBranch: main
  Agent.Source.Git.ShallowFetchDepth: 0

jobs:
  Build_Stage_Package_Module:
    name: Package Module
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Calculate ModuleVersion (GitVersion)
        id: GitVersion
        run: |
          Write-Output "Running pipeline not necessary.....next steps should be skipped"
          exit 1
        shell: pwsh
      - name: Build & Package Module
        shell: pwsh
        run: 'Write-Host "Run Build"'
      - name: Publish Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.buildArtifactName }}
          path: ${{ env.buildFolderName }}/

  Test_Stage_test_windows_ps:
    name: Windows (Windows PowerShell)
    runs-on: windows-latest
    needs:
      - Build_Stage_Package_Module
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.buildArtifactName }}
          path: ${{ env.buildFolderName }}/
      - name: Run Tests
        shell: powershell
        run: 'Write-Host Test'
      - name: Publish Test Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/
          name: CodeCoverageWinPS51
